apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resolutionrequests-cleaner
rules:
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - resolutionrequests.resolution.tekton.dev
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
