apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: opentour-infra-resolutionrequests-cleaner

resources:
 - namespace.yaml
 - serviceaccount.yaml
 - clusterrole.yaml
 - clusterrolebinding.yaml
 - configmap.yaml
 - job.yaml
