apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "OpenTour Infra"
    openshift.io/requester: system:masters
  labels:
    kubernetes.io/metadata.name: opentour-infra-resolutionrequests-cleaner
  name: opentour-infra-resolutionrequests-cleaner
spec: {}
