---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-{{ .Values.namespacePermissions.user }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namespacePermissions.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  namespace: openshift-gitops
  name: openshift-gitops-argocd-application-controller
