apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  version: v2.4
  tracing:
    type: Jaeger
    sampling: 1000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
    prometheus:
      enabled: true
  mode: MultiTenant
  policy:
    type: Istiod
  telemetry:
    type: Istiod
