apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  version: v2.2
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
